<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.zhl.it</groupId>
		<artifactId>it-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>it-common</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>common</name>
	<description>it-common</description>
	<packaging>pom</packaging>
	<modules>
		<module>common-db</module>
		<module>common-redis</module>
		<module>common-services</module>
		<module>common-utils</module>
	</modules>
</project>